"""empty message

Revision ID: a709c721929e
Revises: a1b2c3d4e5f6
Create Date: 2026-05-05 01:06:33.536979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a709c721929e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_radar_images_extent'), table_name='radar_images', postgresql_using='gist')
    op.drop_index(op.f('ix_radar_images_image_timestamp'), table_name='radar_images')
    op.drop_index(op.f('ix_radar_images_location'), table_name='radar_images')
    op.drop_table('radar_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('image_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('datotif_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extent', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('width_px', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height_px', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_dbz', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('storm_pixel_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('radar_images_pkey')),
    sa.UniqueConstraint('filename', name=op.f('radar_images_filename_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_radar_images_location'), 'radar_images', ['location'], unique=False)
    op.create_index(op.f('ix_radar_images_image_timestamp'), 'radar_images', ['image_timestamp'], unique=False)
    op.create_index(op.f('idx_radar_images_extent'), 'radar_images', ['extent'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
